#!/usr/bin/python

env = Environment()

env.Append(LIBS = ['boost_python', 'exiv2'])
env.Append(CPPPATH = ['/usr/include/python2.4'])

env.SharedLibrary('libpyexiv2', ['libpyexiv2.cpp', 'libpyexiv2_wrapper.cpp'])
