#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os.path

env = Environment()

libs = ['boost_python', 'exiv2']
env.Append(LIBS=libs)

pythonIncPath = os.path.join(sys.prefix, 'include', 'python' + sys.version[:3])
env.Append(CPPPATH=[pythonIncPath])

cppSources = ['libpyexiv2.cpp', 'libpyexiv2_wrapper.cpp']

env.SharedLibrary('libpyexiv2', cppSources)
