#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os.path

env = Environment()

libs = ['boost_python', 'exiv2']
env.Append(LIBS=libs)

pythonIncPath = os.path.join(sys.prefix, 'include', 'python' + sys.version[:3])
env.Append(CPPPATH=[pythonIncPath])

cppSources = ['libpyexiv2.cpp', 'libpyexiv2_wrapper.cpp']

# Build shared library libpyexiv2
libpyexiv2 = env.SharedLibrary('libpyexiv2', cppSources)

pythonLibPath = os.path.join(sys.prefix, 'lib', 'python' + sys.version[:3])
# install the Python module, invoked using 'scons install'
env.Alias(target='install', source=env.Install(pythonLibPath, libpyexiv2))
env.Alias(target='install', source=env.Install(pythonLibPath, 'pyexiv2.py'))
